### ISSUE TITLE
Can you please add coingecko or more exchange 

### ISSUE THREAD

**Issue by Willstar44** [walkjivefly/LOC-Extension#12] opened 2021-04-27 13:05 UTC
Could you please add coingecko

there already way to get it running on google scrips , however I rather google didn't snoop on my documents  

https://blog.coingecko.com/import-coingecko-cryptocurrency-data-into-google-sheets/

**Comment by walkjivefly** [comment] 2021-04-27 14:01
Dupe of https://github.com/walkjivefly/LOC-Extension/issues/11.

**Closed by walkjivefly** 2021-04-27 14:01 UTC
