### ISSUE TITLE
Supporting coinmarketcap

### ISSUE THREAD

**Issue by lifeiscrypto** [walkjivefly/LOC-Extension#3] opened 2017-12-25 17:27 UTC
According to this https://github.com/ccxt/ccxt/wiki/Exchange-Markets coinmarketcap is one of the exchanges supported. However if I write on a cell something like: =CCXT("coinmarketcap","eth/btc","last") I get a "Unknown coinmarketcap pair: ETH/BTC" error. Do we have to express the pairs on a different format for this case?

**Comment by walkjivefly** [comment] 2017-12-25 18:21
Hi, coinmarketcap is a funny one because it's an aggregator and works differently in ccxt than a regular exchange. I've been messing with it for the last couple of days because I wanted access to its "global" properties like total market cap and bitcoin dominance.

The version embedded in LOC has some problems. I've pulled in some of the changes from the latest version (as of yesterday, 1.10.402) to try to solve them.  

The ticker pairs are different for coinmarketcap than for regular exchanges. It creates a ticker pair for every single coin against its base fiat currencies, eg: BTC/GBP, BTC/USD, ETH/GBP, ETH/USD. The regular exchange pairs, like ETH/BTC, aren't there.

It would be convenient to pull tickers from coinmarketcap because there's no worry about whether they have a price for the coin you're interested in and (when/if I get it working) the prices are cached so there's no network delay for each lookup. For simple portfolio tracking with no need for realtime price tracking it would be perfect.

In the meantime you're better off getting the price from a regular exchange. Or, if your Python skills are better than mine (which would not be difficult!) hack the code and submit a pull request ;-)

**Comment by lifeiscrypto** [comment] 2017-12-25 22:05
@walkjivefly thank you for your quick answer. I am not a programmer so I am afraid I can't help much more than testing and reporting. I tried now doing CCXT("coinmarketcap","btc/eur","last"), which I didn't try before, and it works perfectly, actually that's all I would need on my side as I am good with using fiat (eur) for getting each of the prices for the coins I hold.

If getting pairs like BTC/GBP, BTC/USD, ETH/GBP, ETH/USD is already working, what would be the next goal? getting pairs like BTC/ETH from coinmarketcap? I am not sure I understood the reason why is it better for now taking the price from a regular exchange.

I really appreciate that you made this tool available. I wanted to keep away from Excel or Google Spreadsheets, and use open source software to keep track of my savings, and that's how I found this great LibreOffice extension.

**Comment by walkjivefly** [comment] 2017-12-25 22:37
The quick answer was down to lucky timing, but I'm glad it was helpful and the extension is doing what you need. The next goal for me for coinmarketcap is getting the global information and getting caching working. I'm close on both of those. I don't intend to even try to make coin/coin pairs work, although that could be useful.

Thanks for the feedback. Out of interest, what OS are you running on? Did you have any issues installing the extension?

**Comment by walkjivefly** [comment] 2017-12-26 03:09
@lifeiscrypto I have just released v[0.2.3](https://github.com/walkjivefly/LOC-Extension/tree/v0.2.3) which has a few enhancements to the coinmarket cap results and which includes caching for several exchanges. Details in the [README](https://github.com/walkjivefly/LOC-Extension/blob/master/README.md)

**Comment by lifeiscrypto** [comment] 2017-12-26 08:02
@walkjivefly I am on a Windows 10 (with fall creators update installed) and running the latest version of LibreOffice. I didn't have any issues installing 0.2.2, but I am now having issues installing 0.2.3 (alpha 0.4)
 (I removed 0.2.2 first as I have read that the extension upgrading doesn't always work well). Error message is attached.
![capture](https://user-images.githubusercontent.com/32542490/34351112-e6c340b8-ea1a-11e7-916c-4f89abd95c6c.PNG)

Another thing I noticed yesterday is that for most of my coins I can fetch price info from coinmarketcap, but for 3 of them (maybe because they are not so popular??) it doesn't fetch the price, and however conmarketcap have those coins listed on their website. The pairs I noticed with the problem are:
ccxt("coinmarketcap","aeon/eur","last")
ccxt("coinmarketcap","zcl/eur","last")
ccxt("coinmarketcap","plbt/eur","last")
There will be more but from my coins, those 3 out of 20 are not working, I wonder if it is just the API of coinmarketcap not giving that data, but I can do for example https://api.coinmarketcap.com/v1/ticker/aeon/?convert=EUR

**Comment by walkjivefly** [comment] 2017-12-26 16:41
Eeek! You're using Windows. I hope you made a system snapshot before trying to upgrade the extension. I did update the README to say Windows users should stick to 0.2.2

So far I've seen 2 varieties of installation errors on Windows. The first regards temp files used for logging. v0.2.2 was a special version with no logging to avoid the error. 
The second complains about a missing file with a space in the pathname, eg: ...\LOC (1).oxt...
I don't know if it's really the space in the name that causes the problem but it is a common factor. I suspect the way to check and avoid it is to rename the download to LOC.oxt before attempting to install.

Those 3 tickers work for me. Do you get an unhelpful "Exception encountered" result (which came from the extension) or a LibreOffice error message? Improving the content of the result in the case of errors is on my list of things to do but not a high priority because I can just look in the log for more details. Unfortunately that option doesn't exist on windows at the moment. I mentioned my ropey Python skills, right?

If you do get "Exception encountered" then the most likely reason is a timeout trying to get the result from coinmarketcap (or any other source). Try it again and it will probably work.

**Comment by lifeiscrypto** [comment] 2017-12-26 20:56
Opps ok, I haven't read the README, and as soon as I saw that you had a new version I went ahead and tried it. Well, I managed to fix it, I removed 0.2.3 and installed 0.2.2 again and I had issues. Then I went to C:\Users\{username}\AppData\Roaming\LibreOffice\4\user\ and I sent the folder "Extensions" to the Recycle Bin, then I opened again LibreOffice and 0.2.2 was still there and now working, weird! I think it was actually enough with removing 0.2.3 and installing 0.2.2 and then closing every process related to LibreOffice, and opening it again.

Also I could find out that:
- If I try to install 0.2.2 with name LOC (1).oxt then it throws an error, so the spaces on the file name are indeed a problem
- If I try to install 0.2.3 with name LOC.oxt it still doesn't work, it gives me this error: 
![image](https://user-images.githubusercontent.com/32542490/34364387-cf71d116-ea85-11e7-9746-c4a83c08c759.png)

Regarding the 3 tickers that they don't work for me, no idea why! I get this error, as if those pairs do not exist:
![image](https://user-images.githubusercontent.com/32542490/34364296-b1652fd4-ea84-11e7-89d5-d44c9e92f27e.png)

**Comment by walkjivefly** [comment] 2017-12-27 04:04
The file not found error during installation of 0.2.3 on Windows is the same as issue [#1](https://github.com/walkjivefly/LOC-Extension/issues/1) and is the reason why there is a v0.2.2

I have reproduced the installation error when there is a space in the extension file name. It's a LibreOffice problem. It's definitely the space and not the brackets in the name (put there by your browser when downloading the extension if a previous version is still present in your download location) which causes the problem. I'll update the README to warn about it.

I have reproduced the unknown pair error in 0.2.[012]. It's a problem with ccxt and fixed by ccxt in the changes I've pulled in to 0.2.3. That doesn't help you very much, @lifeiscrypto, but when I get round to fixing logging on Windows you'll be golden :-)

Thanks for reporting the issues and helping me improve the extension.

**Closed by walkjivefly** 2017-12-27 04:04 UTC

**Comment by walkjivefly** [comment] 2017-12-27 04:34
Opened LibreOffice bug [114708](https://bugs.documentfoundation.org/show_bug.cgi?id=114708) for the problem installing an extension with a space (put there by the browser) in the filename.

**Comment by lifeiscrypto** [comment] 2017-12-27 08:42
Thank you!, I'll keep an eye to the repo for any new updates

**Comment by lifeiscrypto** [comment] 2017-12-31 08:21
@walkjivefly I've got version 0.2.3 working on Windows. I tried this over the pre-release version of LibreOffice 6.0, but Its like to work also on LibreOffice 5. There are two steps I had to do:
1. Go to C:\Users\{user}\AppData\Roaming\LibreOffice and remove whatever is there (in my case I just have a folder with name "4"). This is not related with 0.2.3 issue but just with the fact that every time I have to update/reinstall the extension it won't let me if I don't delete this folder. So with a clean install this step is not necessary.
2. I just had to create a folder "C:\tmp\" which in Windows doesn't exist by default (at least on my installation the default temp folder is "C:\Temp\"  and my guess is that in Linux it does exist, so this is where the problem was coming from. I did this just by reading the error message I was getting when trying to install 0.2.3 and realizing there was a "File not found" error there, that were referencing to "C:\tmp\".

Now if I browse to "C:\tmp\" on File Explorer, I can see 2 files: LOC_9004 and LOC_9228 (maybe the log files?). Hopefully this help you to fix the problem for everyone on Windows.

Now I can use all the pairs I need from coinmarketcap :)

**Comment by walkjivefly** [comment] 2017-12-31 17:27
@lifeiscrypto Yes, you're right on both counts. But having to delete the entire customisations folder is a bit extreme in my view. It's about the only thing that works, and that's on LibreOffice, but there should be a better way. And at least one user reported that adding the c:\tmp folder didn't work for them. Maybe that was a windows version problem or maybe they didn't delete the entire customisations folder. 

Yes, those are the log files. They can be useful when all you see in the sheet is "Exception encountered" to know what the actual exception was. Most often it'll be exchange unavailable, which generally means the connection timed out.

Anyway, I'm glad it's working for you. I'm busy with other stuff at the moment but at some point I'll either fix the logging on windows so the installation works or just document the need to add the logging folder before attempting to install.

Happy New Year!
