### ISSUE TITLE
file not found exception on install

### ISSUE THREAD

**Issue by mortee** [walkjivefly/LOC-Extension#10] opened 2020-01-27 02:53 UTC
#### LOC-Extension version: 
0.2.3

#### Platform you're running it on: 
Windows 8.1 64 bit, LibreOffice 6.3.4.2 (x64)

#### Expected behaviour: 
extension installs without issues

#### Actual behaviour:
I get the following error dialog upon trying to install:
(com.sun.star.uno.RuntimeException) { { Message = "<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\\\tmp\\\\LOC_11096', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 104, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\mortee\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu10352x8tz09.tmp_\\LOC-0.2.3.oxt\\loc.py\", line 38, in <module>\X000a    fh = logging.FileHandler(logfile, mode='a', encoding=None, delay=False)\X000a  File \"C:\\Program Files\\LibreOffice\\program\\python-core-3.5.9\\lib\\logging\\__init__.py\", line 1014, in __init__\X000a    StreamHandler.__init__(self, self._open())\X000a  File \"C:\\Program Files\\LibreOffice\\program\\python-core-3.5.9\\lib\\logging\\__init__.py\", line 1043, in _open\X000a    return open(self.baseFilename, self.mode, encoding=self.encoding)\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by walkjivefly** [comment] 2020-01-27 07:54
Duplicate of https://github.com/walkjivefly/LOC-Extension/issues/2

Windows users are STRONGLY advised to make a Windows system snapshot before installing or upgrading ANY LibreOffice extension and to only use v0.2.2 LOC-Extension until further notice.

**Comment by mortee** [comment] 2020-01-27 11:45
Sorry, I failed to look among closed issues too! Will try 0.2.2

**Comment by walkjivefly** [comment] 2020-01-27 12:47
No worries. I hope 0.2.2 works OK for you. I haven't touched the extension since 0.2.3 and have no way of testing on any variety of Windows.

If it works for you, great! If not, maybe you can try to fix it ;-)

**Closed by walkjivefly** 2020-01-27 12:47 UTC
